:libraryVersion: 2.0.0

= velcro-parts

A bunch of little android libraries for throwing in your application
to avoid having to lookup, copy and pasting from one application to another.

= The Parts

== BetterViewAnimator

Adapted from Jake Wharton's U2020 application, `BetterViewanimator` is a view animator with an added
methods `setDisplayedChildId` and `getDisplayedChildId` allowing you to do animations using
resource ids.

=== Usage

Add

[source, groovy, subs='attributes']
----
compile 'com.andrewreitz.velcro:velcro-bindableadapter:{libraryVersion}'
----

to your build.gradle and extend `BetterViewAnimator`.

== BindableAdapter

Adapted from Jake Wharton's U2020 application, `BindableAdapter` is an adapter that makes it easier
inflate and get view reusage from Adapters for Lists.

=== Usage

Add

[source, groovy, subs='attributes']
----
compile 'com.andrewreitz.velcro:velcro-bindableadapter:{libraryVersion}'
----

to your build.gradle and extend `BindableAdapter`.

== BindableRecyclerAdapter

Similar to `BindableAdapter` except you use it with `RecyclerViews`. Simplifies the process and
abstracts away the need for view holders.

=== Usage

Add

[source, groovy, subs='attributes']
----
compile 'com.andrewreitz.velcro:velcro-bindablerecycleradapter:{libraryVersion}'
----

to your dependencies and extend `BindableRecyclerAdapter`.

== InfiniteScroll

Adapted from Panayiotis Papageorgiou's infinite scrolling post, InfiniteScroll contains the class
`InfiniteScrollListener` for extension and handing off to ListViews for easy infinite scrolling.

=== Usage

Add

[source, groovy, subs='attributes']
----
compile 'com.andrewreitz.velcro:velcro-infinitescroll:{libraryVersion}'
----

to your dependencies and extend `InfiniteScrollListener`. Then attach it to the ListView you want
infinite scrolling on.

== Velcro Rx

A bunch of useful RxJava classes.
(Mostly deprecated for RxJava 1.x and Retrofit 1.x)

* `EndlessObserver` from Jake Wharton's U2020 app, is an observer that only requires you to implement
`onNext`, and thus "never ends"
* `EndObserver` from Jake Wharton's U2020 app, that introduces a new method on the Observer `onEnd`.
This method is called when `onComplete` or `onEnd` is called, always notify you that the Observer
has ended receiving events.
* `RetrofitObserver` is an Observer to use with Retrofit. It will automatically give you an error
as a `RetrofitError`. If there is an error other than retrofit you can handle this by overriding
`nonRetrofitError`. This class also has the same qualities as `EndObserver`.

=== Usage

Add
[source, groovy, subs='attributes']
----
compile 'com.andrewreitz.velcro:velcro-rx:{libraryVersion}'
----

to your dependencies and extends the classes as you need.

== Velcro Rx Android

Simple Easy to Use Transformation for Android Schedulers.

[source, groovy, subs='attributes']
----
compile 'com.andrewreitz.velcro:velcro-rx-android:{libraryVersion}'
----

= License

====
Copyright 2017 Andrew Reitz
Copyright 2014 Jake Wharton
Copyright 2014 Panayiotis Papageorgiou

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
====
